services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'jradtilbrook/spell-check']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
