steps:
  # - label: ":sparkles:"
  #   plugins:
  #     docker-compose#v3.7.0:
  #       run: lint
  #   soft_fail: true

  # - label: ":docker: :hammer:"
  #   command: docker-compose run tests

  - label: Check spelling
    command: ls
    plugins:
      - jradtilbrook/spell-check:
          pattern: '*.md'
