steps:
  - label: ":sparkles:"
    plugins:
      plugin-linter#v2.0.0:
        id: jradtilbrook/spell-check

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.7.0:
        run: tests

  - label: Check spelling
    command: ls
    plugins:
      - jradtilbrook/spell-check:
          pattern: '*.md'
