steps:
  - label: ":sparkles:"
    plugins:
      docker-compose#v3.7.0:
        run: lint
    soft_fail: true

  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.7.0:
        run: tests

  - command: ls
    plugins:
      - jradtilbrook/spell-check#1.0.0:
          pattern: ‘*.md’
