#!/bin/bash
set -euo pipefail

export CHECK_NAME="$BUILDKITE_PLUGIN_SPELL_CHECK_PATTERN"

echo $PWD
ls
SPELLING_ERRORS=$(docker run -v $PWD:/spell -e CHECK_DIR=/spell -e CHECK_NAME johnroesler/docker-spell-check)
echo SPELLING_ERRORS: \"${SPELLING_ERRORS}\"
echo $@
$@

if [[ -z "${SPELLING_ERRORS}" ]]; then
    buildkite-agent annotate --style 'success' "No spelling errors found"
else
    buildkite-agent annotate --style 'warning' "The following errors have been found in these files: ${SPELLING_ERRORS}"
fi
